services:
  hoyo-calendar:
    image: 1w32yhttyayqam-ghcr.xuanyuan.run/trrrrw/hoyo-calendar-backend:latest
    container_name: hoyo-calendar-backend
    restart: always
    volumes:
      - /vol1/1000/DockerAppData/hoyo-calendar:/src/release
